- name: Install and enable batstat
  tags: systemd
  block:
    - name: Install libnotify Pacman
      when: ansible_os_family == 'Archlinux'
      tags:
        - Archlinux
      community.general.pacman:
        name: libnotify
        state: present
        reason: explicit
      become: true
      become_user: root

    - name: Install libnotify APT
      when: ansible_os_family == 'Debian'
      tags:
        - Debian
      ansible.builtin.apt:
        name: libnotify-dev
        state: present
      become: true
      become_user: root

    - name: Clone batstat
      ansible.builtin.git:
        repo: 'https://github.com/RicNord/batstat.git'
        dest: "{{ home }}/repos/usr/.ansible/batstat"
        clone: true
        update: true
      register: batstat
      become: true
      become_user: "{{ user }}"

    - name: Check if batstat exists
      ansible.builtin.stat:
        path: /usr/local/bin/batstat
      register: batexist

    - name: Install batstat
      ansible.builtin.import_tasks:
        file: make_install.yaml
      vars:
        path: "{{ home }}/repos/usr/.ansible/batstat"
      when: batstat.changed or not batexist.stat.exists
