- name: Install dmenu slock
  ansible.builtin.package:
    name:
      - dmenu
      - slock
    state: present
  become: true
  become_user: root

- name: Install suckless dwm/st dependencies
  block:
    - name: Install st/dwm dependencies for Debian
      when: ansible_os_family == 'Debian'
      tags:
        - Debian
      ansible.builtin.apt:
        name:
          - libxft-dev
          - libx11-dev
          - libxinerama-dev
        state: present
      become: true
      become_user: root

    - name: Install st/dwm dependencies for Arch
      when: ansible_os_family == 'Archlinux'
      tags:
        - Archlinux
      community.general.pacman:
        name:
          - libx11
        state: present
        reason: explicit
      become: true
      become_user: root

- name: Install suckless dwm
  block:
    - name: Clone dwm
      ansible.builtin.git:
        repo: 'https://github.com/RicNord/dwm.git'
        dest: "{{ home }}/repos/usr/.ansible/dwm"
        clone: true
        update: true
      register: dwm
      become: true
      become_user: "{{ user }}"

    - name: Install dwm
      ansible.builtin.import_tasks:
        file: make_install.yaml
      vars:
        path: "{{ home }}/repos/usr/.ansible/dwm"
      when: dwm.changed

- name: Install suckless slstatus
  block:
    - name: Clone slstatus
      ansible.builtin.git:
        repo: 'https://github.com/RicNord/slstatus.git'
        dest: "{{ home }}/repos/usr/.ansible/slstatus"
        clone: true
        update: true
      register: slstatus
      become: true
      become_user: "{{ user }}"

    - name: Install slstatus
      ansible.builtin.import_tasks:
        file: make_install.yaml
      vars:
        path: "{{ home }}/repos/usr/.ansible/slstatus"
      when: slstatus.changed

- name: Install suckless st
  block:
    - name: Clone st
      ansible.builtin.git:
        repo: 'https://github.com/RicNord/st.git'
        dest: "{{ home }}/repos/usr/.ansible/st"
        clone: true
        update: true
      register: st
      become: true
      become_user: "{{ user }}"

    - name: Install st
      ansible.builtin.import_tasks:
        file: make_install.yaml
      vars:
        path: "{{ home }}/repos/usr/.ansible/st"
      when: st.changed

- name: Install suckless farbfeld
  block:
    - name: Install farbfeld dependencies for Arch
      when: ansible_os_family == 'Archlinux'
      tags:
        - Archlinux
      community.general.pacman:
        name:
          - libpng
          - libjpeg-turbo
        state: present
        reason: explicit
      become: true
      become_user: root

    - name: Install farbfeld dependencies for Debian
      when: ansible_os_family == 'Debian'
      tags:
        - Debian
      ansible.builtin.apt:
        name:
          - libpng-dev
          - libjpeg8
        state: present
      become: true
      become_user: root

    - name: Clone farbfeld
      ansible.builtin.git:
        repo: 'https://github.com/RicNord/farbfeld.git'
        dest: "{{ home }}/repos/usr/.ansible/farbfeld"
        clone: true
        update: true
      register: farbfeld
      become: true
      become_user: "{{ user }}"

    - name: Install farbfeld
      ansible.builtin.import_tasks:
        file: make_install.yaml
      vars:
        path: "{{ home }}/repos/usr/.ansible/farbfeld"
      when: farbfeld.changed

- name: Install suckless sent
  block:
    - name: Install sent dependencies for Arch
      when: ansible_os_family == 'Archlinux'
      tags:
        - Archlinux
      community.general.pacman:
        name:
          - libx11
          - libxft
        state: present
        reason: explicit
      become: true
      become_user: root

    - name: Install sent dependencies for Debian
      when: ansible_os_family == 'Debian'
      tags:
        - Debian
      ansible.builtin.apt:
        name:
          - libxft-dev
          - libx11-dev
        state: present
      become: true
      become_user: root

    - name: Clone sent
      ansible.builtin.git:
        repo: 'https://github.com/RicNord/sent.git'
        dest: "{{ home }}/repos/usr/.ansible/sent"
        clone: true
        update: true
      register: sent
      become: true
      become_user: "{{ user }}"

    - name: Install sent
      ansible.builtin.import_tasks:
        file: make_install.yaml
      vars:
        path: "{{ home }}/repos/usr/.ansible/sent"
      when: sent.changed

- name: Install batstat
  ansible.builtin.import_tasks: batstat.yaml

- name: Install nnn and plugins
  ansible.builtin.import_tasks: nnn.yaml
