# Adding dependencies for installing apt keys
- name: Adding depencnecies
  tags:
    - debian
    - apt
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - wget
      - apt-transport-https

- name: Get DPKG architecture
  ansible.builtin.shell:
    cmd: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false
  check_mode: no

- name: Create /etc/apt/keyrings directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add post invoke script to delete automatically created sources.list files
  ansible.builtin.template:
    src: 100post-invoke
    dest: /etc/apt/apt.conf.d/100post-invoke
    owner: root
    group: root
    mode: '0644'

- name: Add additional repos to apt
  notify: apt update
  block:
    # Microsoft
    - name: Add microsoft apt repository
      block:
        - name: Copy microsoft.pgp
          ansible.builtin.copy:
            src: microsoft.pgp
            dest: /etc/apt/keyrings/microsoft.pgp
            owner: root
            group: root
            mode: '0755'

        - name: Add azure-cli
          ansible.builtin.template:
            src: azure-cli.sources.jinja
            dest: /etc/apt/sources.list.d/azure-cli.sources
            owner: root
            group: root
            mode: '0644'

        - name: Add vscode
          tags:
            - X
          ansible.builtin.template:
            src: vscode.sources.jinja
            dest: /etc/apt/sources.list.d/vscode.sources
            owner: root
            group: root
            mode: '0644'

    ## Google
    - name: Add google apt repository
      block:
        - name: Copy google.pgp
          ansible.builtin.copy:
            src: google.pgp
            dest: /etc/apt/keyrings/google.pgp
            owner: root
            group: root
            mode: '0755'


        - name: Add google-chrome
          tags:
            - X
          ansible.builtin.template:
            src: google-chrome.sources.jinja
            dest: /etc/apt/sources.list.d/google-chrome.sources
            owner: root
            group: root
            mode: '0644'

    # Docker
    - name: Add docker apt repository
      block:
        - name: Copy docker.pgp
          ansible.builtin.copy:
            src: docker.pgp
            dest: /etc/apt/keyrings/docker.pgp
            owner: root
            group: root
            mode: '0755'

        - name: Add docker
          ansible.builtin.template:
            src: docker.sources.jinja
            dest: /etc/apt/sources.list.d/docker.sources
            owner: root
            group: root
            mode: '0644'

    # Hashicorp
    - name: Add hashicorp apt repository
      block:
        - name: Copy hashicorp.pgp
          ansible.builtin.copy:
            src: hashicorp.pgp
            dest: /etc/apt/keyrings/hashicorp.pgp
            owner: root
            group: root
            mode: '0755'

        - name: Add hashicorp
          ansible.builtin.template:
            src: hashicorp.sources.jinja
            dest: /etc/apt/sources.list.d/hashicorp.sources
            owner: root
            group: root
            mode: '0644'

    # Spotify
    - name: Add spotify apt repository
      tags:
        - X
      block:
        - name: Copy spotify.pgp
          ansible.builtin.copy:
            src: spotify.pgp
            dest: /etc/apt/keyrings/spotify.pgp
            owner: root
            group: root
            mode: '0755'

        - name: Add spotify
          ansible.builtin.template:
            src: spotify.sources.jinja
            dest: /etc/apt/sources.list.d/spotify.sources
            owner: root
            group: root
            mode: '0644'

    # github
    - name: Add github apt repository
      block:
        - name: Copy github.pgp
          ansible.builtin.copy:
            src: github.pgp
            dest: /etc/apt/keyrings/github.pgp
            owner: root
            group: root
            mode: '0755'

        - name: Add github-cli
          ansible.builtin.template:
            src: github-cli.sources.jinja
            dest: /etc/apt/sources.list.d/github-cli.sources
            owner: root
            group: root
            mode: '0644'

    # Zabbly (Incus)
    - name: Add zabbly/incus apt repository
      when: ansible_distribution_version is version('24.04', '<')
      block:
        - name: Copy zabbly.pgp
          ansible.builtin.copy:
            src: zabbly.pgp
            dest: /etc/apt/keyrings/zabbly.pgp
            owner: root
            group: root
            mode: '0755'

        - name: Add Incus
          ansible.builtin.template:
            src: incus.sources.jinja
            dest: /etc/apt/sources.list.d/incus.sources
            owner: root
            group: root
            mode: '0644'

    # Trivy
    - name: Add trivy apt repository
      block:
        - name: Copy trivy.pgp
          ansible.builtin.copy:
            src: trivy.pgp
            dest: /etc/apt/keyrings/trivy.pgp
            owner: root
            group: root
            mode: '0755'

        - name: Add trivy
          ansible.builtin.template:
            src: trivy.sources.jinja
            dest: /etc/apt/sources.list.d/trivy.sources
            owner: root
            group: root
            mode: '0644'

## Update and install packages
- name: Force all notified handlers to run, (apt update)
  ansible.builtin.meta: flush_handlers

- name: Install apt X packages
  tags:
    - X
  ansible.builtin.apt:
    pkg:
      - arandr # Frontend for xrandr
      - autorandr # Auto detect connected displays
      - code # Bloat
      - dmenu
      - dunst # Notification deamon
      - filezilla # FTP SFTP client
      - firefox
      - gimp
      - google-chrome-stable
      - libnotify-dev # Send desktop notifications
      - libreoffice
      - maim # take screenshots
      - fonts-noto # Meta pkg of fonts
      - qbittorrent
      - redshift
      - slock
      - spotify-client
      - torbrowser-launcher
      - virt-viewer # Used by incus for RDP to consol
      - wireshark
      # Missing in ubuntu pkg manager - wmname # Set the name of your window manager
      - zathura
      - zathura-pdf-poppler
    state: present

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - acpi # Power Managment - reacts to events
      - azure-cli
      - bash-completion
      - bat
      - build-essential
      - conntrack
      - containerd.io # Docker engine
      - curl
      - dkms # Dynamic Kernel Module Support, used by eg. viritual box
      - dnsutils # nslookup etc
      - docker-buildx-plugin # Docker engine
      - docker-ce-cli # Docker engine
      - docker-ce # Docker engine
      - docker-compose-plugin # Docker engine
      - entr # Run arbitrary commands when files change
      - ethtool # util for network drivers and hardware, nic
      - fd-find
      - fswatch # Filesystem watcher recommended by neovim
      - fzf
      - gdb
      - gdisk # GPT disk partitioning
      - gh
      - git
      - gnome-keyring # Can be used by python-keyring, dep of eg. Twine
      - gnupg
      - gzip
      - hping3
      - htop
      - ifuse # Mount iOS
      - incus
      - iperf3 # speed test tool for network
      - iptraf-ng # Network monitor tool
      - jq
      - libcap-ng-dev # analyse system for apps that have too much privleges
      - libglib2.0-dev
      - libimobiledevice-utils # collection of cli for iOS devices, eg, idevicebackup2
      - linux-headers-generic
      - lshw # list hardware
      - lsof # List Open files
      - lxc
      - macchanger
      - make
      - man-db
      - moreutils
      - ncdu # Ncurses disk analyser
      - net-tools
      # - networkmanager?
      - ngrep
      - nmap
      - openconnect
      - openssh-client
      - openssl
      - pandoc
      - parallel
      - pass
      - pulsemixer
      - python3-pip
      - ranger
      - ripgrep
      - rsync
      - shellcheck
      - shfmt
      - socat # Multipurpose relay
      - speedtest-cli
      - sq # gpg alternative
      - tcpdump
      - terraform
      #      - terragrunt # TODO Manual install
      - tldr
      - tmux
      - tox
      - traceroute
      - tree
      - trivy
      - tshark # wireshark
      - unbound # dns resolver, build dependancy of OVN
      - unifont # font pkg
      - unrar
      - unzip
      - vim-gtk3
      - xclip # x clipboard
      - xsel # x clipboard
      - xterm
      - zip
    state: present

- name: Install apt X packages 24.04+
  tags:
    - X
  when: ansible_distribution_version is version('24.04', '>=')
  ansible.builtin.apt:
    pkg:
      - nsxiv
    state: present
