# Adding dependencies for installing apt keys
- name: Adding depencnecies
  tags:
    - debian
    - apt
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - wget
      - apt-transport-https

- name: Get DPKG architecture
  ansible.builtin.shell:
    cmd: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false
  check_mode: no

- name: Create /etc/apt/keyrings directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add post invoke script to delete automatically created sources.list files
  ansible.builtin.template:
    src: 100post-invoke
    dest: /etc/apt/apt.conf.d/100post-invoke
    owner: root
    group: root
    mode: '0644'

# Adding additional repositorys to APT
# Microsoft
- name: Add microsoft apt repository
  block:
    - name: Copy microsoft.pgp
      ansible.builtin.copy:
        src: microsoft.pgp
        dest: /etc/apt/keyrings/microsoft.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add azure-cli
      ansible.builtin.template:
        src: azure-cli.sources.jinja
        dest: /etc/apt/sources.list.d/azure-cli.sources
        owner: root
        group: root
        mode: '0644'

    - name: Add vscode
      ansible.builtin.template:
        src: vscode.sources.jinja
        dest: /etc/apt/sources.list.d/vscode.sources
        owner: root
        group: root
        mode: '0644'

## Google
- name: Add google apt repository
  block:
    - name: Copy google.pgp
      ansible.builtin.copy:
        src: google.pgp
        dest: /etc/apt/keyrings/google.pgp
        owner: root
        group: root
        mode: '0755'


    - name: Add google-chrome
      ansible.builtin.template:
        src: google-chrome.sources.jinja
        dest: /etc/apt/sources.list.d/google-chrome.sources
        owner: root
        group: root
        mode: '0644'

# Docker
- name: Add docker apt repository
  block:
    - name: Copy docker.pgp
      ansible.builtin.copy:
        src: docker.pgp
        dest: /etc/apt/keyrings/docker.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add docker
      ansible.builtin.template:
        src: docker.sources.jinja
        dest: /etc/apt/sources.list.d/docker.sources
        owner: root
        group: root
        mode: '0644'

# Hashicorp
- name: Add hashicorp apt repository
  block:
    - name: Copy hashicorp.pgp
      ansible.builtin.copy:
        src: hashicorp.pgp
        dest: /etc/apt/keyrings/hashicorp.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add hashicorp
      ansible.builtin.template:
        src: hashicorp.sources.jinja
        dest: /etc/apt/sources.list.d/hashicorp.sources
        owner: root
        group: root
        mode: '0644'

# Spotify
- name: Add spotify apt repository
  block:
    - name: Copy spotify.pgp
      ansible.builtin.copy:
        src: spotify.pgp
        dest: /etc/apt/keyrings/spotify.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add spotify
      ansible.builtin.template:
        src: spotify.sources.jinja
        dest: /etc/apt/sources.list.d/spotify.sources
        owner: root
        group: root
        mode: '0644'

# github
- name: Add github apt repository
  block:
    - name: Copy github.pgp
      ansible.builtin.copy:
        src: github.pgp
        dest: /etc/apt/keyrings/github.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add github-cli
      ansible.builtin.template:
        src: github-cli.sources.jinja
        dest: /etc/apt/sources.list.d/github-cli.sources
        owner: root
        group: root
        mode: '0644'

## Update and install packages
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true
- name: Install apt X packages
  tags:
    - X
  ansible.builtin.apt:
    pkg:
      - arandr # Frontend for xrandr
      - autorandr # Auto detect connected displays
      - code # Bloat
      - dmenu
      - dunst # Notification deamon
      - filezilla # FTP SFTP client
      - firefox
      - gimp
      - google-chrome-stable
      - libnotify-dev # Send desktop notifications
      - libreoffice
      - maim # take screenshots
      - fonts-noto # Meta pkg of fonts
      - qbittorrent
      - redshift
      - slock
      - spotify-client
      - torbrowser-launcher
      - virt-viewer # Used by incus for RDP to consol
      # Missing in ubuntu pkg manager - wmname # Set the name of your window manager
      - zathura
      - zathura-pdf-poppler
    state: present

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - acpi # Power Managment - reacts to events
      - azure-cli
      - bash-completion
      - bat
      - build-essential
      - curl
      - dkms # Dynamic Kernel Module Support, used by eg. viritual box
      - docker-ce # Docker engine
      - docker-ce-cli # Docker engine
      - containerd.io # Docker engine
      - docker-buildx-plugin # Docker engine
      - docker-compose-plugin # Docker engine
      - entr # Run arbitrary commands when files change
      - fd-find
      - fzf
      - gdb
      - git
      - gh
      - libglib2.0-dev
      - gnupg
      - gzip
      - htop
      - jq
      - linux-headers-generic
      - lxc
      - macchanger
      - make
      - man-db
      - moreutils
      - ncdu # Ncurses disk analyser
      - net-tools
      # - networkmanager?
      - nmap
      - npm # TODO move this
      - openconnect
      - openssh-client
      - pandoc
      - parallel
      - pass
      - pulsemixer
      - python3-pip
      - tox
      - ranger
      - ripgrep
      - rsync
      - sq # gpg alternative
      - shellcheck
      - shfmt
      - terraform
      #      - terragrunt # TODO Manual install
      - thefuck
      - tldr
      - tmux
      - traceroute
      - tree
      - unifont # font pkg
      - unrar
      - unzip
      - vim-gtk3
      - xclip # x clipboard
      - xsel # x clipboard
      - xterm
      - zip
    state: present

- name: Install apt packages 24.04+
  when: ansible_distribution_version is version('24.04', '>=')
  ansible.builtin.apt:
    pkg:
      - incus
    state: present

- name: Install apt X packages 24.04+
  tags:
    - X
  when: ansible_distribution_version is version('24.04', '>=')
  ansible.builtin.apt:
    pkg:
      - nsxiv
    state: present
