# Adding dependencies for installing apt keys
- name: Adding depencnecies
  tags:
    - debian
    - apt
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - wget
      - apt-transport-https

- name: Create /etc/apt/keyrings directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add post invoke script to delete automatically created sources.list files
  ansible.builtin.template:
    src: 100post-invoke
    dest: /etc/apt/apt.conf.d/100post-invoke
    owner: root
    group: root
    mode: '0644'

# Adding additional repositorys to APT
# Microsoft
- name: Add microsoft repo
  block:
    - name: Copy microsoft.pgp
      ansible.builtin.copy:
        src: microsoft.pgp
        dest: /etc/apt/keyrings/microsoft.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add azure-cli
      ansible.builtin.template:
        src: azure-cli.sources.jinja
        dest: /etc/apt/sources.list.d/azure-cli.sources
        owner: root
        group: root
        mode: '0644'

    - name: Add vscode
      ansible.builtin.template:
        src: vscode.sources.jinja
        dest: /etc/apt/sources.list.d/vscode.sources
        owner: root
        group: root
        mode: '0644'

## Google
- name: Add google repo
  block:
    - name: Copy google.pgp
      ansible.builtin.copy:
        src: google.pgp
        dest: /etc/apt/keyrings/google.pgp
        owner: root
        group: root
        mode: '0755'


    - name: Add google-chrome
      ansible.builtin.template:
        src: google-chrome.sources.jinja
        dest: /etc/apt/sources.list.d/google-chrome.sources
        owner: root
        group: root
        mode: '0644'

# Docker
- name: Add docker apt repository
  block:
    - name: Check if docker-archive-keyring.gpg already exist
      ansible.builtin.stat:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
      register: docker_gpg

    - name: Add docker-archive-keyring.gpg
      when: not docker_gpg.stat.exists
      block:
        - name: Download gpg key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /tmp/docker.gpg
            mode: '644'

        - name: Add to keyring
          ansible.builtin.shell:
            cmd: gpg -o /usr/share/keyrings/docker-archive-keyring.gpg --dearmor /tmp/docker.gpg

    - name: Add repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

# Hashicorp
- name: Add hashicorp apt repository
  block:
    - name: Check if hashicorp-archive-keyring.gpg already exist
      ansible.builtin.stat:
        path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      register: hashicorp_gpg

    - name: Add hashicorp-archive-keyring.gpg
      when: not hashicorp_gpg.stat.exists
      block:
        - name: Download gpg key
          ansible.builtin.get_url:
            url: https://apt.releases.hashicorp.com/gpg
            dest: /tmp/hashicorp.gpg
            mode: '644'

        - name: Add to keyring
          ansible.builtin.shell:
            cmd: gpg -o /usr/share/keyrings/hashicorp-archive-keyring.gpg --dearmor /tmp/hashicorp.gpg

    - name: Add repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp


# # TODO CURRENTLY THE pubkey_7A3A762FAFD4A51F is not availible, Use Snap instead
# # Spotify
# - name: Add spotify apt repository
#   block:
#     - name: Check if spotify-archive-keyring.gpg already exist
#       ansible.builtin.stat:
#         path: /usr/share/keyrings/spotify-archive-keyring.gpg
#       register: spotify_gpg
#
#     - name: Add spotify-archive-keyring.gpg
#       block:
#       - name: Download gpg key
#         ansible.builtin.get_url:
#           url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
#           dest: /tmp/spotify.gpg
#           mode: '644'
#
#       - name: Add to keyring
#         ansible.builtin.shell:
#           cmd: gpg -o /usr/share/keyrings/spotify-archive-keyring.gpg --dearmor /tmp/spotify.gpg
#       when: not spotify_gpg.stat.exists
#
#     - name: Add repo
#       ansible.builtin.apt_repository:
#         repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/spotify-archive-keyring.gpg] \
#                http://repository.spotify.com stable non-free"
#         state: present
#         filename: spotify

## Update and install packages
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - arandr
      - autorandr
      - azure-cli
      - bat
      - code
      - curl
      - dmenu
      - dunst
      - fd-find
      - filezilla
      - fzf
      - gdb
      - gimp
      - git
        #      - github-cli
      - libglib2.0-dev
      - gnupg
      - google-chrome-stable
      - gzip
      - htop
      - htop
        #      - incus # official in 24.04 (nobel)
      - jq
      - libnotify-dev
      - lxc
      - macchanger
      - maim
      - make
      - man-db
      - moreutils
      - ncdu
      - net-tools
      - nmap
      - npm
        #      - nsxiv # official in 24.04
      - openconnect
      - openssh-client
      - pandoc
      - parallel
      - pass
      - pulsemixer
      - python3-neovim
      - qbittorrent
      - ranger
      - redshift
      - ripgrep
      - rsync
      - sq
      - shellcheck
      - shfmt
      - slock
      - snapd
      - terraform
        #      - terragrunt # TODO Manual install
      - thefuck
      - tldr
      - tmux
      - torbrowser-launcher
      - traceroute
      - tree
      - unifont
      - unrar
      - unzip
      - vim-gtk3
      - virt-viewer
      - xclip
      - xsel
      - xsel
      - xterm
      - zathura
      - zathura-pdf-poppler
      - zip
    state: present
