#- name: Install AUR packages
#  tags:
#    - arch
#    - packages
#  kewlfft.aur.aur:
#    name: "{{ item }}"
#    state: present
#  become: true
#  become_user: aur_builder
#  loop: "{{ lookup('file', 'files/aur.txt').splitlines() }}"

- name: Install AUR packages
  tags:
    - arch
    - packages
  kewlfft.aur.aur:
    name:
      - google-chrome
      - neovim-git
    state: present
  become: true
  become_user: aur_builder
