- name: Install AUR X packages
  tags:
    - X
    - arch
    - packages
  kewlfft.aur.aur:
    name:
      - google-chrome
      - visual-studio-code-bin # MS release
    state: present
  become: true
  become_user: aur_builder

- name: Install AUR packages
  tags:
    - arch
    - packages
  kewlfft.aur.aur:
    name:
      - neovim-git
      - fswatch # Filesystem watcher recommended by neovim
    state: present
  become: true
  become_user: aur_builder
