---

- name: Apt pkgs
  tags:
    - debian
  ansible.builtin.import_tasks: apt.yaml
  when: ansible_os_family == 'Debian'

- name: Snap pkgs
  ansible.builtin.import_tasks: snap.yaml
  when: ansible_os_family == 'Debian'

- name: Pacman pkgs
  ansible.builtin.import_tasks: pacman.yaml
  when: ansible_os_family == 'Archlinux'

- name: AUR pkgs
  ansible.builtin.import_tasks: aur.yaml
  when: ansible_os_family == 'Archlinux'

...
