- name: Apt pkgs
  tags:
    - Debian
  ansible.builtin.import_tasks: apt.yaml
  when: ansible_os_family == 'Debian'

- name: Snap pkgs
  tags:
    - Debian
  ansible.builtin.import_tasks: snap.yaml
  when: ansible_os_family == 'Debian'

- name: Pacman pkgs
  tags:
    - Archlinux
  ansible.builtin.import_tasks: pacman.yaml
  when: ansible_os_family == 'Archlinux'

- name: AUR pkgs
  tags:
    - Archlinux
  ansible.builtin.import_tasks: aur.yaml
  when: ansible_os_family == 'Archlinux'

- name: Incus
  ansible.builtin.import_tasks: incus.yaml
