- name: Install packman packages
  tags:
    - arch
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
    reason: explicit
  loop: "{{ lookup('file', 'files/pacman.txt').splitlines() }}"
