# iptables are included in base package, and will conflict with nft, needs
# confirmation to be removed.
- name: Use iptables-nft
  ansible.builtin.shell:
    cmd: yes | pacman -S iptables-nft

- name: Install pacman X packages
  tags:
    - X
  community.general.pacman:
    name:
      - arandr # Frontend for xrandr
      - autorandr # Auto detect connected displays
      - code # Bloat
      - discord
      - dmenu
      - dunst # Notification deamon
      - filezilla # FTP SFTP client
      - firefox
      - gimp
      - libnotify # Send desktop notifications
      - libreoffice-still
      - maim # take screenshots
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - noto-fonts
      - nsxiv # Suckless image viwer
      - qbittorrent
      - redshift
      - slock
      - torbrowser-launcher
      - virt-viewer # Used by incus for RDP to consol
      - vlc
      - wmname # Set the name of your window manager
      - zathura
      - zathura-pdf-poppler
    state: present
    reason: explicit

- name: Install pacman packages
  tags:
    - arch
    - packages
  community.general.pacman:
    name:
      - acpi # Power Managment - reacts to events
      - alacritty
      - alsa-utils # Sound utils, TODO remove
      - base-devel
      - bash-completion
      - bat
      - bind # DNS tool. eg nslookup
      - bluez # Bluetooth, TODO make optional
      - bluez-utils # Bluetooth, TODO make optional
      - curl
      - dkms # Dynamic Kernel Module Support, used by eg. viritual box
      - docker
      - docker-compose
      - efibootmgr
      - entr # Run arbitrary commands when files change
      - fd # Find alternative
      - fzf
      - gdb
      - git
      - github-cli
      - glib2 # Low level core lib
      - gnome-keyring # Can be used by python-keyring, dep of eg. Twine
      - gnupg
      - grub # Possibly remove for here
      - gvim
      - gzip
      - htop
      - incus
      - jq
      - linux-headers
      - lxc
      - macchanger
      - make
      - man-db
      - moreutils
      - ncdu # Ncurses disk analyser
      - net-tools
      - networkmanager
      - networkmanager-openconnect
      - networkmanager-openvpn
      - nmap
      - openconnect
      - openssh
      - pandoc-cli
      - parallel
      - pass
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth # TODO make optional
      - pulsemixer
      - python-pip
      - ranger
      - ripgrep
      - rsync
      - sequoia-sq # gpg alternative
      - shellcheck
      - shfmt
      - terraform
      - terragrunt
      - thefuck
      - tldr
      - tmux
      - traceroute
      - tree
      - unrar
      - unzip
      - wget
      - xclip # x clipboard
      - xsel # x clipboard
      - xterm
      - zip
    state: present
    reason: explicit

- name: Install virtualbox
  tags:
    - X
    - arch
    - packages
  community.general.pacman:
    name:
      - linux-headers
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso
      - virtualbox
    state: present
    reason: explicit
