---
- name: Install packman packages
  tags:
    - arch
    - packages
  community.general.pacman:
    name: "{{ item }}"
    update_cache: true
    state: latest
    reason: explicit
  loop: "{{ lookup('file', 'files/pacman.txt').splitlines() }}"

...
