- name: Install packman packages
  tags:
    - arch
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
    reason: explicit
  loop: "{{ lookup('file', 'files/pacman.txt').splitlines() }}"

- name: Install virtualbox
  tags:
    - arch
    - packages
  community.general.pacman:
    name:
      - linux-headers
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso
      - virtualbox
    state: present
    reason: explicit
