#- name: Install packman packages
#  tags:
#    - arch
#    - packages
#  community.general.pacman:
#    name: "{{ item }}"
#    state: present
#    reason: explicit
#  loop: "{{ lookup('file', 'files/pacman.txt').splitlines() }}"
#
- name: Install packman packages
  tags:
    - arch
    - packages
  community.general.pacman:
    name:
      - acpi
      - alacritty
      - alsa-utils
      - arandr
      - autorandr
      - base-devel
      - bash-completion
      - bat
      - bluez
      - bluez-utils
      - code
      - curl
      - discord
      - dkms
      - dmenu
      - docker
      - docker-compose
      - dunst
      - efibootmgr
      - entr
      - fd
      - filezilla
      - firefox
      - fzf
      - gdb
      - gimp
      - git
      - github-cli
      - glib2
      - gnupg
      - grub
      - gvim
      - gzip
      - htop
      - incus
      - jq
      - libnotify
      - libreoffice-still
      - linux-headers
      - lxc
      - macchanger
      - maim
      - make
      - man-db
      - moreutils
      - ncdu
      - net-tools
      - networkmanager
      - networkmanager-openconnect
      - networkmanager-openvpn
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - npm
      - nsxiv
      - okular
      - openconnect
      - openssh
      - pandoc-cli
      - parallel
      - pass
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pulsemixer
      - python-pip
      - python-pipenv
      - python-tox
      - python-virtualenv
      - qbittorrent
      - ranger
      - redshift
      - ripgrep
      - rsync
      - sequoia-sq
      - shellcheck
      - shfmt
      - slock
      - terraform
      - terragrunt
      - thefuck
      - tldr
      - tmux
      - torbrowser-launcher
      - traceroute
      - tree
      - unrar
      - unzip
      - vlc
      - wget
      - wmname
      - xclip
      - xsel
      - xterm
      - zathura
      - zathura-pdf-poppler
      - zip
    state: present
    reason: explicit

- name: Install virtualbox
  tags:
    - arch
    - packages
  community.general.pacman:
    name:
      - linux-headers
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso
      - virtualbox
    state: present
    reason: explicit
