# TODO ensure snap installed

- name: Install Snap packages
  community.general.snap:
    name:
      - slack
      - spotify
      - storage-explorer
      - vlc
    state: present

- name: Install Snap packages classic
  community.general.snap:
    name:
      - alacritty
    classic: true
    state: present
