- name: Install snapd
  ansible.builtin.apt:
    pkg:
      - snapd
    state: present

- name: Install Snap packages
  tags:
    - X
  community.general.snap:
    name:
      - storage-explorer
      - vlc
    state: present

- name: Install Snap packages classic
  community.general.snap:
    name:
      - alacritty
    classic: true
    state: present
