- name: Update packages
  hosts: all
  become: true
  pre_tasks:

    - name: Apt update && apt upgrade
      when: ansible_distribution == 'Debian'
      tags: always
      ansible.builtin.apt:
        upgrade: safe
        update_cache: true

    - name: Pacman.conf multilib
      when: ansible_distribution == "Archlinux"
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: "^#\\[multilib\\]\n#Include = /etc/pacman.d/mirrorlist"
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"

    - name: Pacman.conf ParallelDownloads
      when: ansible_distribution == "Archlinux"
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: "^#ParallelDownloads.*$"
        replace: "ParallelDownloads = 15"

    - name: Pacman -Syu
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        update_cache: true
        upgrade: true

- name: Create {{ user }}
  hosts: all
  become: true
  roles:
    - role: user

- name: Arch setup
  hosts: all
  become: true
  roles:
    - role: arch_setup
      when: ansible_distribution == "Archlinux"

- name: Package manager
  hosts: all
  become: true
  roles:
    - package_manager

- name: User env
  hosts: all
  become: true
  become_user: "{{ user }}"
  roles:
    - dotfiles
    - neovim

- name: Programing languages
  hosts: all
  become: true
  roles:
    - prog_env

- name: Arch setup
  hosts: all
  tags:
    - X
  roles:
    - role: suckless

- name: Gnome config
  hosts: all
  become: true
  roles:
    - role: gnome
      when: ansible_distribution == 'Debian'

- name: Systemd config
  hosts: all
  become: true
  roles:
    - systemd
