- name: Update packages
  hosts: all
  become: true
  pre_tasks:

    - name: Apt update && apt upgrade
      tags:
        - Debian
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        upgrade: safe
        update_cache: true

    - name: Pacman.conf multilib
      tags:
        - Archlinux
      when: ansible_os_family == "Archlinux"
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: "^#\\[multilib\\]\n#Include = /etc/pacman.d/mirrorlist"
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"

    - name: Pacman.conf ParallelDownloads
      tags:
        - Archlinux
      when: ansible_os_family == "Archlinux"
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: "^#ParallelDownloads.*$"
        replace: "ParallelDownloads = 15"

    - name: Pacman -Syu
      tags:
        - Archlinux
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        update_cache: true
        upgrade: true

- name: Create {{ user }}
  hosts: all
  become: true
  roles:
    - role: user

- name: Arch setup
  tags:
    - Archlinux
  hosts: all
  become: true
  roles:
    - role: arch_setup
      when: ansible_os_family == "Archlinux"

- name: Xorg
  tags:
    - X
  hosts: all
  become: true
  roles:
    - role: xorg

- name: Package manager
  hosts: all
  become: true
  roles:
    - package_manager

- name: User env
  hosts: all
  become: true
  become_user: "{{ user }}"
  roles:
    - dotfiles
    - neovim

- name: Programing languages
  hosts: all
  become: true
  roles:
    - prog_env

- name: Suckless
  hosts: all
  tags:
    - X
  roles:
    - role: suckless

      #- name: Gnome config
      #  hosts: all
      #  become: true
      #  roles:
      #    - role: gnome
      #      when: ansible_os_family == 'Debian'

- name: Systemd config
  hosts: all
  become: true
  roles:
    - systemd
