- name: Install light aur package
  when: ansible_os_family == 'Archlinux'
  tags:
    - X
    - Archlinux
  kewlfft.aur.aur:
    name:
      - light
    state: present
  become: true
  become_user: aur_builder

- name: Install light apt package
  when: ansible_os_family == 'Debian'
  tags:
    - X
    - Debian
  ansible.builtin.apt:
    pkg:
      - light
    state: present

- name: Ensure existance of group video
  tags:
    - X
  ansible.builtin.group:
    name: video
    state: present

- name: Add {{ user }} to home
  tags:
    - X
  ansible.builtin.user:
    name: "{{ user }}"
    append: true
    groups:
      - video
