- name: Install dotnet
  tags:
    - Archlinux
    - dotnet
  when: ansible_os_family == 'Archlinux'
  community.general.pacman:
    name:
      - dotnet-runtime
      - dotnet-sdk
    state: present
    reason: explicit
  become: true

- name: Install dotnet
  when: ansible_os_family == 'Debian'
  tags:
    - Debian
    - dotnet
  ansible.builtin.apt:
    pkg:
      - dotnet-runtime-8.0
      - dotnet-sdk-8.0
    state: present
  become: true
