- name: Install dotnet runtime
  tags:
    - Archlinux
    - dotnet
  when: ansible_os_family == 'Archlinux'
  community.general.pacman:
    name:
      - dotnet-runtime
    state: present
    reason: explicit
  become: true

- name: Install dotnet runtime
  when: ansible_os_family == 'Debian'
  tags:
    - Debian
    - dotnet
  ansible.builtin.apt:
    pkg:
      - dotnet-runtime-7.0
      - dotnet-runtime-8.0
    state: present
  become: true
