- name: Install dotnet host arch aur
  tags:
    - Archlinux
    - dotnet
  kewlfft.aur.aur:
    name:
      - dotnet-host-bin
    state: present
  become: true
  become_user: aur_builder

- name: Install dotnet arch aur
  tags:
    - Archlinux
    - dotnet
  kewlfft.aur.aur:
    name:
      - aspnet-runtime-bin
      - dotnet-runtime-bin
      - dotnet-sdk-bin
    state: present
  become: true
  become_user: aur_builder

- name: Install dotnet
  when: ansible_os_family == 'Debian'
  tags:
    - Debian
    - dotnet
  ansible.builtin.apt:
    pkg:
      - dotnet-runtime-8.0
      - dotnet-sdk-8.0
    state: present
  become: true
