- name: Install go Arch
  tags:
    - Archlinux
  when: ansible_os_family == 'Archlinux'
  block:
    - name: Install Go Arch
      tags: go
      become: true
      community.general.pacman:
        name:
          - go
        state: present
        reason: explicit

    - name: Update .bash_ansible
      become: true
      become_user: "{{ user }}"
      ansible.builtin.blockinfile:
        path: "{{ home }}/.bash_ansible"
        block: |
          export PATH="$HOME/go/bin:$PATH"
        marker: "# <!--- {mark} GO ANSIBLE MANAGED BLOCK --->"
        create: true
        mode: '664'
        owner: "{{ user }}"
        group: "{{ user }}"

- name: Add golang apt repository
  tags:
    - Debian
  when: ansible_os_family == 'Debian'
  block:
    - name: Copy golang-ppa.pgp
      ansible.builtin.copy:
        src: golang-ppa.pgp
        dest: /etc/apt/keyrings/golang-ppa.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add golang
      ansible.builtin.template:
        src: golang.sources.jinja
        dest: /etc/apt/sources.list.d/golang.sources
        owner: root
        group: root
        mode: '0644'

    - name: Run the equivalent of "apt-get update" as a separate step
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Apt install go
      become: true
      ansible.builtin.apt:
        pkg:
          - golang-go
        state: present

