
- name: Install Java
  tags: java
  community.general.pacman:
    name:
      - jre11-openjdk
      - jdk11-openjdk
    state: present
    reason: explicit
  when: ansible_os_family == 'Archlinux'

- name: Install Java
  tags:
    - java
  ansible.builtin.apt:
    pkg:
      - default-jre
      - default-jdk
    state: present
  when: ansible_os_family == 'Debian'
