
- name: Install Java
  tags:
    - Archlinux
    - java
  community.general.pacman:
    name:
      - jdk-openjdk
      - jdk17-openjdk
      - jdk11-openjdk
    state: present
    reason: explicit
  become: true
  become_user: root
  when: ansible_os_family == 'Archlinux'

- name: Install Java
  tags:
    - Debian
    - java
  ansible.builtin.apt:
    pkg:
      - default-jdk
    state: present
  become: true
  become_user: root
  when: ansible_os_family == 'Debian'
