- name: Install Lua
  tags:
    - Archlinux
    - lua
  when: ansible_os_family == 'Archlinux'
  community.general.pacman:
    name:
      - luarocks
    state: present
    reason: explicit

- name: Install Lua
  tags:
    - Debian
    - lua
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    pkg:
      - luarocks
    state: present
