- name: Install yamlfmt
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell: |
    go install github.com/google/yamlfmt/cmd/yamlfmt@latest

- name: Install Rust package
  become: true
  become_user: "{{ user }}"
  community.general.cargo:
    name:
      - stylua # Lua code formatter
    executable: "{{ home }}/.cargo/bin/cargo"
    state: present

- name: Install npm pkg
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  loop:
    - markdownlint-cli
    - neovim

- name: Install python tools
  block:
    - name: Tools on Arch
      tags:
        - Archlinux
      when: ansible_os_family == 'Archlinux'
      community.general.pacman:
        name:
          - python-black
          - python-isort
        state: present
        reason: explicit
      become: true
      become_user: root

    - name: Tools on debian
      tags:
        - Debian
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        pkg:
          - black
          - isort
        state: present
      become: true
      become_user: root
