- name: Install Go tools
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell: |
    go install {{ item.path }}
  args:
    executable: /bin/bash
    creates: "{{ home }}/go/bin/{{ item.name }}"
  loop:
    - {name: "dlv", path: "github.com/go-delve/delve/cmd/dlv@latest"}
    - {name: "goimports", path: "golang.org/x/tools/cmd/goimports@latest"}
    - {name: "golangci-lint", path: "github.com/golangci/golangci-lint/cmd/golangci-lint@latest"} # not recommended, but do it anyway to avoid AUR and snap
    - {name: "go-licenses", path: "github.com/google/go-licenses@latest"}
    - {name: "gotestsum", path: "gotest.tools/gotestsum@latest"}
    - {name: "staticcheck", path: "honnef.co/go/tools/cmd/staticcheck@latest"}
    - {name: "yamlfmt", path: "github.com/google/yamlfmt/cmd/yamlfmt@latest",}

- name: Cargo install
  become: true
  become_user: "{{ user }}"
  community.general.cargo:
    name:
      - stylua # Lua code formatter
    executable: "{{ home }}/.cargo/bin/cargo"
    state: present

- name: Install npm pkg
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  loop:
    - markdownlint-cli
    - neovim
