- name: Git clone dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/RicNord/dotfiles.git'
    dest: "{{ home }}/repos/usr/dotfiles"
    clone: true
    update: true
  register: dotfiles
  become_user: "{{ user }}"

- name: Deploy user dotfiles
  ansible.builtin.command: /bin/bash ./deploy.sh -fv
  become: true
  become_user: "{{ user }}"
  args:
    chdir: "{{ home }}/repos/usr/dotfiles"
  when: dotfiles.changed

- name: Deploy system dotfiles
  ansible.builtin.command: /bin/bash ./deploy.sh -efv
  become: true
  become_user: root
  args:
    chdir: "{{ home }}/repos/usr/dotfiles"
  when: dotfiles.changed

- name: Install .meta_root
  become: true
  become_user: "{{ user }}"
  ansible.builtin.import_tasks: meta_root.yaml
