- name: Install rsync
  block:
    - name: Archlinux rsync
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name: rsync
        state: present
        update_cache: false
        reason: explicit

    - name: Debian rsync
      when: ansible_distribution == "Debian"
      ansible.builtin.apt:
        pkg: rsync
        state: present

- name: Sync etc/ dotfiles
  become: true
  ansible.posix.synchronize:
    src: dotfiles/etc/
    dest: etc/
    delete: false
    dirs: false
    mode: "push"
    rsync_opts:
      - "--include=etc/"
