- name: Install rsync
  block:
    - name: Archlinux rsync
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        name: rsync
        state: present
        update_cache: false
        reason: explicit

    - name: Debian rsync
      when: ansible_distribution == "Debian"
      ansible.builtin.apt:
        pkg: rsync
        state: present

- name: Sync home/ dotfiles
  become: true
  become_user: "{{ user }}"
  ansible.posix.synchronize:
    src: dotfiles/
    dest: "{{ home }}/"
    archive: false
    group: false
    owner: false
    perms: false
    recursive: true
    times: false
    delete: false
    dirs: false
    mode: "push"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=deploy.sh"
      - "--exclude=README.md"
      - "--exclude=etc"
