---

- name: Copy X resources
  tags:
    - X
  block:
    - name: Copy xinitrc
      ansible.builtin.copy:
        src: dotfiles/.xinitrc
        dest: "{{ home }}/"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Copy xprofile
      ansible.builtin.copy:
        src: dotfiles/.xprofile
        dest: "{{ home }}/"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Copy XCompose
      ansible.builtin.copy:
        src: dotfiles/.XCompose
        dest: "{{ home }}/"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

- name: Copy bash config
  tags:
    - bash
  block:
    - name: Copy bashrc
      ansible.builtin.copy:
        src: dotfiles/.bashrc
        dest: "{{ home }}/"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Copy bash_aliases
      ansible.builtin.copy:
        src: dotfiles/.bash_aliases
        dest: "{{ home }}/"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: dotfiles/.gitconfig
    dest: "{{ home }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

- name: Copy .ssh/config
  ansible.builtin.copy:
    src: dotfiles/.ssh/config
    dest: "{{ home }}/.ssh/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

- name: Copy vsCode
  ansible.builtin.copy:
    src: dotfiles/.config/Code/User
    dest: "{{ home }}/.config/Code/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

- name: Copy vimrc
  ansible.builtin.copy:
    src: dotfiles/.vimrc
    dest: "{{ home }}/.vimrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

...
