- name: slock
  ansible.builtin.import_tasks: slock.yaml

- name: xidlehook
  ansible.builtin.import_tasks: xidlehook.yaml

- name: Logind config
  ansible.builtin.import_tasks: logind.yaml

- name: Systemd services
  tags: systemd
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Enable NetworkManager
      tags:
        - Archlinux
      ansible.builtin.systemd:
        name: NetworkManager
        state: started
        enabled: true
      when: "'NetworkManager' in services and ansible_os_family == 'Archlinux'"

    - name: Disable bluetooth
      ansible.builtin.systemd:
        name: bluetooth.service
        state: stopped
        enabled: false
      when: "'bluetooth' in services"

    - name: Enable timesyncd
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: started
        enabled: true
      when: "'systemd-timesyncd' in services"
