- name: Systemd Slock
  tags: systemd
  block:
    - name: Copy slock on sleep unit file
      ansible.builtin.copy:
        src: slock@.service
        dest: /etc/systemd/system/slock@.service
        owner: root
        group: root
      become: true
      become_user: root

    - name: Enable Slock service
      ansible.builtin.systemd:
        name: slock@{{ user }}.service
        enabled: true
        daemon_reload: true

- name: Logind config
  ansible.builtin.import_tasks: logind.yaml

- name: Systemd services
  tags: systemd
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Enable NetworkManager
      when: ansible_distribution == "Archlinux"
      ansible.builtin.systemd:
        name: NetworkManager
        state: started
        enabled: true

    - name: Enable bluetooth
      ansible.builtin.systemd:
        name: bluetooth.service
        state: stopped
        enabled: false
      when: "'bluetooth' in services"

    - name: Enable timesyncd
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: started
        enabled: true
