- name: Install light package
  tags:
    - packages
    - X
  kewlfft.aur.aur:
    name:
      - light
    state: present
  become: true
  become_user: aur_builder

- name: Ensure existance of group video
  tags:
    - X
  ansible.builtin.group:
    name: video
    state: present

- name: Add {{ user }} to home
  tags:
    - X
  ansible.builtin.user:
    name: "{{ user }}"
    append: true
    groups:
      - video
