- name: Create user
  tags:
    - arch
  ansible.builtin.import_tasks: user.yaml

- name: Create AUR user
  ansible.builtin.import_tasks: aur_user.yaml

- name: Install yay
  ansible.builtin.import_tasks: yay.yaml

- name: Install Xorg
  ansible.builtin.import_tasks: xorg.yaml

- name: Install Light
  ansible.builtin.import_tasks: light.yaml

- name: Install batstat
  ansible.builtin.import_tasks: batstat.yaml

- name: Touch .meta_root
  ansible.builtin.import_tasks: meta_root.yaml
