- name: Create AUR user
  ansible.builtin.import_tasks: aur_user.yaml

- name: Install yay
  ansible.builtin.import_tasks: yay.yaml

- name: Install Xorg
  ansible.builtin.import_tasks: xorg.yaml

- name: Install Light
  ansible.builtin.import_tasks: light.yaml
