
- name: Install X pkgs
  tags:
    - X
    - arch
    - packages
  community.general.pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xsetroot
      - xorg-apps
        # misc
      - noto-fonts
    state: present
    reason: explicit

- name: Graphics driver
  tags:
    - X
  block:
    - name: Include multilib repository
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: "^#\\[multilib\\]\n#Include = /etc/pacman.d/mirrorlist"
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"

    - name: Run the equivalent of "pacman -Sy" as a separate step
      community.general.pacman:
        update_cache: true

          # TODO discover platform
    - name: Install graphics drivers
      community.general.pacman:
        name:
          - mesa
          - vulkan-intel
            #          These caused problems for electron applications
            #          - xf86-video-intel
            #          - intel-media-driver
          - lib32-mesa

- name: Block TTY and killing of X server
  tags:
    - X
  ansible.builtin.copy:
    src: 10-x-hardening.conf
    dest: "/etc/X11/xorg.conf.d/10-x-hardening.conf"
  become: true
  become_user: root
