- name: Install dependencies
  tags:
    - arch
  community.general.pacman:
    name:
      - go
    state: present
    reason: explicit
  become: true
  become_user: root

- name: Git clone yay
  tags:
    - arch
  become: true
  become_user: aur_builder
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: "/home/aur_builder/repos/usr/yay"
    clone: true
    update: true
  register: yay
  notify:
    - Makepkg yay

- name: Check if yay is installed
  ansible.builtin.shell:
    cmd: which yay
    executable: /bin/bash
  changed_when: false
  register: yayinstalled
  failed_when: yayinstalled.rc not in [0,1]
  notify:
    - Makepkg yay
