- name: Add wsl.conf
  when: ansible_facts['os_family'] == "Debian" and "WSL2" in ansible_facts['kernel']
  ansible.builtin.template:
    src: wsl.conf
    dest: /etc/wsl.conf
    owner: root
    group: root
    mode: '0644'

- name: Install wsl pkgs
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    pkg:
      - wslu # wsl utils, example can open links in windows browser with xdg-open
    state: present
