- name: Add neovim apt repository
  tags:
    - Debian
  when: ansible_os_family == 'Debian'
  become: true
  become_user: root
  block:
    - name: Copy neovim.pgp
      ansible.builtin.copy:
        src: neovim-ppa.pgp
        dest: /etc/apt/keyrings/neovim-ppa.pgp
        owner: root
        group: root
        mode: '0755'

    - name: Add neovim.sources
      ansible.builtin.template:
        src: neovim.sources.jinja
        dest: /etc/apt/sources.list.d/neovim.sources
        owner: root
        group: root
        mode: '0644'

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: true

    - name: Install nvim
      tags: nvim
      ansible.builtin.apt:
        name:
          - neovim
          - python3-neovim
        state: present
        update_cache: true
      become: true
      become_user: root

- name: Neovim on Arch
  tags:
    - Archlinux
  when: ansible_os_family == 'Archlinux'
  block:
    - name: Install nvim
      kewlfft.aur.aur:
        name: neovim-git
        state: present
      become: true
      become_user: aur_builder


    - name: Pacman -Syy
      ansible.builtin.command: pacman -Syy
      become: true
      become_user: root

    - name: Install pynvim
      community.general.pacman:
        name: python-pynvim
        state: present
      become: true
      become_user: root

- name: Install neovim config
  block:
    - name: Clone nvim
      ansible.builtin.git:
        repo: 'https://github.com/RicNord/nvim.git'
        dest: "{{ home }}/repos/usr/.ansible/nvim"
        clone: true
        update: true
      register: nvim
      become: true
      become_user: "{{ user }}"

    - name: Deploy nvim config
      ansible.builtin.command:
        cmd: ./deploy-repo.sh
      args:
        chdir: "{{ home }}/repos/usr/.ansible/nvim"
      when: nvim.changed
      become_user: "{{ user }}"
